#!/bin/bash

cd ~/CycleSafeServer

TOMCAT_INIT=/etc/init.d/tomcat7;
OLD_DEPLOYMENT=/var/lib/tomcat7/webapps/ROOT

#get changes from git
echo "Updating from remote repository..."
git reset --hard origin/master;
git pull;

chmod +x deploy
chmod +x sox_splitter.sh

#shutdown tomcat while we redeploy
echo "Stopping tomcat..."
sudo $TOMCAT_INIT stop;

#remove previous build
echo "Removing previous build..."
sudo rm -r "$OLD_DEPLOYMENT";
sudo rm "$OLD_DEPLOYMENT.war";

#build with dependencies
echo "Making new build..."
sudo mvn package;

#start tomcat again
echo "Restarting tomcat..."
sudo $TOMCAT_INIT start;

#Removing these should speed up the build
#if it breaks stuff put them back in
#remove target dir
#echo "Cleaning up compile time dependencies.."
#sudo mvn clean;